gems:
  #- ci_reporter
  - buildr-bnd >= 0.0.4
  - buildr-iidea >= 0.0.8
  - buildr-ipojo >= 0.0.1

artifacts:
  ipojo_eventadmin: org.apache.felix:org.apache.felix.ipojo.handler.eventadmin:jar:1.6.0
  osgi_core: org.apache.felix:org.osgi.core:jar:1.4.0
  osgi_compendium: org.apache.felix:org.osgi.compendium:jar:1.4.0
  hibernate_persistence: org.hibernate.javax.persistence:hibernate-jpa-2.0-api:jar:1.0.0.Final
  hibernate_annotation: org.hibernate:hibernate-annotations:jar:3.5.3-Final
  hibernate_commons_annotations: org.hibernate:hibernate-commons-annotations:jar:3.2.0.Final
  hibernate_validator: org.hibernate:hibernate-validator:jar:4.0.2.GA
  hibernate_entitymanager: org.hibernate:hibernate-entitymanager:jar:3.5.1-Final
  hibernate_core: org.hibernate:hibernate-core:jar:3.5.1-Final
  javax_validation: javax.validation:validation-api:jar:1.0.0.GA
  javax_transaction: javax.transaction:jta:jar:1.1
  javassist: javassist:javassist:jar:3.9.0.GA
  dom4j: dom4j:dom4j:jar:1.6.1
  slf4j_api: org.slf4j:slf4j-api:jar:1.5.8
  slf4j_jdk14: org.slf4j:slf4j-jdk14:jar:1.5.8
  jcl_over_slf4j: org.slf4j:jcl-over-slf4j:jar:1.5.8
  commons_collections: commons-collections:commons-collections:jar:3.1
  antlr: antlr:antlr:jar:2.7.6
