gems:
 #- ci_reporter
 - buildr-bnd = 0.0.5
 - buildr-iidea = 0.0.9

artifacts:
 core: org.eclipse.persistence:org.eclipse.persistence.core:jar:2.1.1
 jpa: org.eclipse.persistence:org.eclipse.persistence.jpa:jar::2.1.1
 asm: org.eclipse.persistence:org.eclipse.persistence.asm:jar::2.1.1
 antlr: org.eclipse.persistence:org.eclipse.persistence.antlr:jar::2.1.1
 persistence: org.eclipse.persistence:javax.persistence:jar::2.0.2
 derby: org.apache.derby:derby:jar:10.6.1.0
 derbytools: org.apache.derby:derbytools:jar:10.6.1.0
 validation: org.apache.geronimo.specs:geronimo-validation_1.0_spec:jar:1.0
 jta: org.apache.geronimo.specs:geronimo-jta_1.1_spec:jar:1.1.1
 bval: org.apache.bval:org.apache.bval.bundle:jar:0.2-incubating
 jms: org.apache.geronimo.specs:geronimo-jms_1.1_spec:jar:1.1.1
 slf4j_api: org.slf4j:slf4j-api:jar:1.5.8
 slf4j_jdk14: org.slf4j:slf4j-jdk14:jar:1.5.8
 jcl_over_slf4j: org.slf4j:jcl-over-slf4j:jar:1.5.8
 commons_lang: commons-lang:commons-lang:jar:2.4
 commons_butils: commons-beanutils:commons-beanutils:jar:1.8.3

repositories:
 remote:
  - http://www.stocksoftware.com.au/repositories/external
  - http://www.stocksoftware.com.au/repositories/releases
  - http://mirror.aarnet.edu.au/pub/eclipse/rt/eclipselink/maven.repo
  - https://repository.apache.org/content/repositories/releases
  - http://www.ibiblio.org/maven2
  - http://www.aQute.biz/repo
 